test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

employee:
    resource: "@EmployeeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
