employee_homepage:
    path:     /employeedetails
    defaults: { _controller: EmployeeBundle:Default:index }
    
employee_addemployee:
    path:     /add_employee
    defaults: { _controller: EmployeeBundle:Default:create }
    
employee_employeeslist:
    path:     /employees/list
    defaults: { _controller: EmployeeBundle:Default:getEmployees }
    
employee_employee_detail:
    path:       /show/empolyee/{id}
    defaults: { _controller: EmployeeBundle:Default:getEmployeeDetail }
    
employee_max_salary:
    path:       /second_max_salary
    defaults: { _controller: EmployeeBundle:Default:getSecondMaxSalary }
    
employee_add_company:
    path:       /add_company
    defaults: { _controller: EmployeeBundle:Default:addCompany }
    
employe_list_companies:
    path:       /companies/list
    defaults: { _controller: EmployeeBundle:Default:listCompanies }
    
company_delete:
    path: /company/delete/{id}
    defaults: {_controller: EmployeeBundle:Default:deleteCompany }
    
company_edit:
    path: /company/edit/{id}
    defaults: {_controller: EmployeeBundle:Default:editCompany }
    
department_show_form:
    path: /department/add
    defaults: { _controller: EmployeeBundle:Default:showDepartmentForm }
    
department_save:
    path: /department/save
    defaults: { _controller: EmployeeBundle:Default:saveDepartmentForm }
    
departments_list:
    path: /department/list
    defaults: { _controller: EmployeeBundle:Default:listDepartments }

department_delete:
    path: /department/delete/{id}
    defaults: {_controller: EmployeeBundle:Default:deleteDepartment }