services:
#    employee.example:
#        class: EmployeeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    employee.message:
        class: EmployeeBundle\Service\MessageGenerator
        arguments: []
   
    employees.Details:
        class: EmployeeBundle\Service\Employees
        arguments: ['@doctrine.orm.entity_manager']
