product_homepage:
    path:     /ProductHomePage
    defaults: { _controller: ProductBundle:Default:index }
    
user_registration:
    path: /UserRegistration
    defaults: { _controller: ProductBundle:Default:register }
    
user_registration_action:
    path: /UserRegistration/save
    defaults: { _controller: ProductBundle:Default:registerSave }

product_add_people:
    path: /product/people/add
    defaults: { _controller: ProductBundle:Default:addPeople }
    
product_people_save:
    path: /product/people/save
    defaults: { _controller: ProductBundle:Default:savePeopleForm }
    
insert_states:
    path: /state/add
    defaults: { _controller: ProductBundle:Default:insertStates }